### ISSUE TITLE
No longer works with Arduino SAMD Boards 1.8.x

### ISSUE THREAD

**Issue by srw777** [adafruit/Adafruit_NeoMatrix_ZeroDMA#4]
- Arduino board:  Maduino Zero CAN-BUS
- Arduino IDE version:  1.8.13

- List the steps to reproduce the problem below: 

I used this library in a project a few years ago and it worked great.  I recently tried updating that project and discovered that this library no longer works with the latest "Arduino SAMD Boards" version. (1.8.13 - not to be confused with my IDE version which is also the same) To rule out my code, I loaded the "matrixtest" example provided with this library and it also failed to compile.  I reverted to Boards version 1.6.21 and it works fine.  I assume something significant must have changed in Hardware SPI between 1.6 and 1.8.

The error is:

Arduino: 1.8.13 (Windows 10), Board: "Arduino Zero (Native USB Port)"
C:\Users\Scott\Documents\Arduino\libraries\Adafruit_DMA_neopixel_library\Adafruit_NeoPixel_ZeroDMA.cpp: In member function 'boolean Adafruit_NeoPixel_ZeroDMA::begin(SERCOM*, Sercom*, uint8_t, uint8_t, uint8_t, uint8_t, SercomSpiTXPad, SercomRXPad, EPioType)':
C:\Users\Scott\Documents\Arduino\libraries\Adafruit_DMA_neopixel_library\Adafruit_NeoPixel_ZeroDMA.cpp:140:57: error: invalid new-expression of abstract class type 'arduino::HardwareSPI'
       new SPIClass(sercom, miso, sck, mosi, padTX, padRX);
                                                         ^
In file included from C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\libraries\SPI/SPI.h:24:0,
                 from C:\Users\Scott\Documents\Arduino\libraries\Adafruit_DMA_neopixel_library\Adafruit_NeoPixel_ZeroDMA.h:6,
                 from C:\Users\Scott\Documents\Arduino\libraries\Adafruit_DMA_neopixel_library\Adafruit_NeoPixel_ZeroDMA.cpp:35:
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:104:7: note:   because the following virtual functions are pure within 'arduino::HardwareSPI':
 class HardwareSPI
       ^~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:109:21: note: 	virtual uint8_t arduino::HardwareSPI::transfer(uint8_t)
     virtual uint8_t transfer(uint8_t data) = 0;
                     ^~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:110:22: note: 	virtual uint16_t arduino::HardwareSPI::transfer16(uint16_t)
     virtual uint16_t transfer16(uint16_t data) = 0;
                      ^~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:111:18: note: 	virtual void arduino::HardwareSPI::transfer(void*, size_t)
     virtual void transfer(void *buf, size_t count) = 0;
                  ^~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:114:18: note: 	virtual void arduino::HardwareSPI::usingInterrupt(int)
     virtual void usingInterrupt(int interruptNumber) = 0;
                  ^~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:115:18: note: 	virtual void arduino::HardwareSPI::notUsingInterrupt(int)
     virtual void notUsingInterrupt(int interruptNumber) = 0;
                  ^~~~~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:116:18: note: 	virtual void arduino::HardwareSPI::beginTransaction(arduino::SPISettings)
     virtual void beginTransaction(SPISettings settings) = 0;
                  ^~~~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:117:18: note: 	virtual void arduino::HardwareSPI::endTransaction()
     virtual void endTransaction(void) = 0;
                  ^~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:120:18: note: 	virtual void arduino::HardwareSPI::attachInterrupt()
     virtual void attachInterrupt() = 0;
                  ^~~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:121:18: note: 	virtual void arduino::HardwareSPI::detachInterrupt()
     virtual void detachInterrupt() = 0;
                  ^~~~~~~~~~~~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:123:18: note: 	virtual void arduino::HardwareSPI::begin()
     virtual void begin() = 0;
                  ^~~~~
C:\Users\Scott\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.13\cores\arduino/api/HardwareSPI.h:124:18: note: 	virtual void arduino::HardwareSPI::end()
     virtual void end() = 0;
                  ^~~
exit status 1
Error compiling for board Arduino Zero (Native USB Port).

**Comment by srw777** [comment]
My apologies.  After updating Adafruit_DMA_neopixel_library to the latest version it works fine with SAMD 1.8.13.

**Comment by tekktrik** [comment]
Marking as closed since the issue is resolved
